# 6.try-catch-finally-return

Q: try{}里有一个return语句,那么紧跟在这个try后的finally {}里的code会不会被执行,什么时候被执行,在return前还是后?

A: 会执行,在return前执行.

## 代码验证
``` java
public class Main {
    public static void main(String[] args) {
        String result = test();
        System.out.println(result);
    }

    private static String test() {
        try {
            System.out.println("try");
            return "return from try block";
        } catch (Exception e) {
            return "exception";
        } finally {
            System.out.println("finally");
//            return "return from finally block";
        }
    }
}
```
结果:
```
try
finally
return from try block
```

## 假如finally{}有return会怎样?
```java
public class Main {
    public static void main(String[] args) {
        String result = test();
        System.out.println(result);
    }

    private static String test() {
        try {
            System.out.println("try");
            return "return from try block";
        } catch (Exception e) {
            return "exception";
        } finally {
            System.out.println("finally");
            return "return from finally block";
        }
    }
}
```
结果:
```
try
finally
return from finally block
```

结论: finally{}中的return会覆盖try{}中的return.